const players =[
    {
        id:0,
        nombre: "Borro",
        posicion: "atancante",
        cal: 4,
    },
    {
        id:1,
        nombre: "Chavi",
        posicion: "defensivo",
        cal: 3,
    },
    {
        id:2,
        nombre: "Chango",
        posicion: "defensivo",
        cal: 4,
    },
    {
        id:3,
        nombre: "Colo",
        posicion: "atacante",
        cal: 3,
    },
    {
        id:4,
        nombre: "Cow",
        posicion: "atacante",
        cal: 2,
    },
    {
        id:5,
        nombre: "Fabi",
        posicion: "arquero",
        cal: 3,
    },
    {
        id:6,
        nombre: "Guille",
        posicion: "defensivo",
        cal: 4,
    },
    {
        id:7,
        nombre: "Gus",
        posicion: "atacante",
        cal: 3,
    },
    {
        id:8,
        nombre: "Harry",
        posicion: "atacante",
        cal: 3,
        
    },
    {
        id:9,
        nombre: "Imper",
        posicion: "defensivo",
        cal: 3,
    },
    {
        id:10,
        nombre: "Fer M",
        posicion: "atacante",
        cal: 5,
    },
    {
        id:11,
        nombre: "Leito",
        posicion: "defensivo",
        cal: 4,
    },
    {
        id:12,
        nombre: "Luke",
        posicion: "arquero",
        cal: 5,
    },
    {
        id:13,
        nombre: "Lukini",
        posicion: "atacante",
        cal: 5,
    },
    {
        id:14,
        nombre: "Marian",
        posicion: "atacante",
        cal: 3,
    },
    {
        id:15,
        nombre: "Negro",
        posicion: "defensivo",
        cal: 3,
    },
    {
        id:16,
        nombre: "Chinchu",
        posicion: "atacante",
        cal: 3,
    },
    {
        id:17,
        nombre: "Renzo",
        posicion: "defensivo",
        cal: 4,
    },
    {
        id:18,
        nombre: "Rody",
        posicion: "atacante",
        cal: 5,
    },
    {
        id:19,
        nombre: "Tasca",
        posicion: "atacante",
        cal: 5,
    },
    {
        id:20,
        nombre: "Tito",
        posicion: "defensivo",
        cal: 4,
    },
    {
        id:22,
        nombre: "Tincho",
        posicion: "atacante",
        cal: 3,
    },
    {
        id:23,
        nombre: "Ale",
        posicion: "defensivo",
        cal: 3,
    },
    {
        id:24,
        nombre: "Lucho",
        posicion: "defensivo",
        cal: 3,
    },
    {
        id:25,
        nombre: "Lince",
        posicion: "atacante",
        cal: 3,
    },
]